env:
  es6: true
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2018
  #ecmaVersion: 2018 (9) (node 10)
  #ecmaVersion: 2019 (10) (node 12)
  #ecmaVersion: 2020 (11) (node 14)

rules:
  no-unused-vars: ["error", { args: none }]

extends: ["eslint:recommended" ]
