name: Node.js LTS versions
author: Matt Simerson
description: Get list of maintained LTS Node.js versions (active + maintenance)
runs:
  using: 'node12'
  main: 'main.js'
outputs:
  lts:
    description: maintained LTS versions of node.js